ALTER TABLE materiales
  ADD COLUMN IF NOT EXISTS technical_sheet_url TEXT,
  ADD COLUMN IF NOT EXISTS sena_plate VARCHAR(50),
  ADD COLUMN IF NOT EXISTS marca_id INTEGER REFERENCES marcas(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS custodian_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS location VARCHAR(150),
  ADD COLUMN IF NOT EXISTS purchase_date DATE,
  ADD COLUMN IF NOT EXISTS unit_value NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS total_value NUMERIC(12,2);
